In [ ]:
# imports
import pandas as pd
import numpy as np
import cv2
import matplotlib.pyplot as plt
import insightface
from insightface.app import FaceAnalysis
from insightface.data import get_image as ins_get_image
import os
import glob
import ipywidgets
from tqdm import tqdm

In [ ]:
# load LFW all names
path_to_csv = "/home/sho/Insightface-Face-Recognition/img/LFW/lfw_allnames.csv"
path_to_img = "/home/sho/Insightface-Face-Recognition/img/LFW/lfw-deepfunneled/lfw-deepfunneled/"

df = pd.read_csv(path_to_csv)
print(df.shape)
df.head()

(5749, 2)

              name  images
0          AJ_Cook       1
1         AJ_Lamas       1
2    Aaron_Eckhart       1
3      Aaron_Guiel       1
4  Aaron_Patterson       1

In [ ]:
# add an ID column for each person
df['ID'] = range(len(df))

# add a column for each person images path
df['name_path'] = path_to_img + df['name']

df.head()

,name,images,ID,name_path
0,AJ_Cook,1,0,/home/sho/Insightface-Face-Recognition/img/LFW...
1,AJ_Lamas,1,1,/home/sho/Insightface-Face-Recognition/img/LFW...
2,Aaron_Eckhart,1,2,/home/sho/Insightface-Face-Recognition/img/LFW...
3,Aaron_Guiel,1,3,/home/sho/Insightface-Face-Recognition/img/LFW...
4,Aaron_Patterson,1,4,/home/sho/Insightface-Face-Recognition/img/LFW...

In [ ]:
# img to embedding

def img_to_embedding(img_path):

    # read img
    read_img = cv2.imread(img_path)

    # init face analysis app
    app = FaceAnalysis()

    # to show images
    """plt.imshow(read_img[:,:,::-1])
    plt.show()"""

    # to prepare images 
    app.prepare(ctx_id=0)
    try:
        faces = app.get(read_img)[0]['embedding']

        return faces
    
    except Exception as e:
        print(f"Error in embedding function for {img_path}: {e}")
        return None

In [5]:
test = '/home/sho/Insightface-Face-Recognition/img/LFW/lfw-deepfunneled/lfw-deepfunneled/Alimzhan_Tokhtakhounov/Alimzhan_Tokhtakhounov_0001.jpg'
img_to_embedding(test)

/home/sho/anaconda3/envs/face-gen-notebook/lib/python3.13/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:118: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/sho/.insightface/models/buffalo_l/1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/sho/.insightface/models/buffalo_l/2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/sho/.insightface/models/buffalo_l/det_10g.onnx detection [1, 3, '?', '?'] 127.5 128.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/sho/.insightface/models/buffalo_l/genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: /home/sho/.insightface/models/buffalo_l/w600k_r50.onnx recognition ['None', 3, 112, 112] 127.5 127.5
set det-size: (640, 640)

array([ 3.03388268e-01, -1.16919637e+00,  9.98994231e-01,  1.16959047e+00,
       -5.30745149e-01,  1.49588096e+00, -4.98472273e-01,  9.64588344e-01,
       -1.49702832e-01, -1.54247060e-01, -5.37674785e-01,  4.34018224e-01,
        3.37939799e-01, -8.90786648e-01,  3.68266612e-01, -1.61088562e+00,
       -7.11225569e-01, -6.69753432e-01, -6.14364326e-01, -6.71382189e-01,
        1.20678830e+00, -3.47654745e-02, -3.78919691e-02, -9.20734882e-01,
       -4.56830561e-02, -9.57407236e-01, -1.11521721e+00,  1.70577931e+00,
        1.09602904e+00,  7.83460259e-01, -5.41847527e-01,  3.82343620e-01,
       -6.57285810e-01,  1.06513333e+00, -1.59068525e+00,  3.75739098e-01,
       -1.86584139e+00, -1.42555952e+00,  6.11202002e-01,  5.21783769e-01,
        3.44935954e-01, -8.31741929e-01,  1.20857105e-01, -2.67411679e-01,
       -5.15638232e-01, -2.47151747e-01,  1.38737285e+00,  3.29087138e-01,
        7.59184062e-01, -1.71835339e+00,  1.07944459e-02, -5.17993569e-01,
       -9.89799142e-01,  1.69444382e-01, -6.58947647e-01,  1.66922998e+00,
       -1.46256536e-01, -2.00690240e-01, -7.66957402e-01,  1.90648818e+00,
       -9.18508291e-01, -4.27832395e-01,  4.92047310e-01, -1.93906355e+00,
        5.85326672e-01,  1.13293099e+00,  8.34884942e-02,  1.28187466e+00,
       -1.48278689e+00, -9.66908514e-01, -1.28686100e-01, -6.06302083e-01,
        1.25010520e-01,  2.44094253e-01,  2.16314673e-01, -4.72502947e-01,
       -9.26345646e-01, -1.23617128e-01,  5.18884659e-01,  1.53434300e+00,
       -1.13767028e+00,  7.62915462e-02, -5.69222450e-01, -1.51803207e+00,
        9.54885840e-01,  1.09016430e+00, -3.34980994e-01, -7.21151829e-01,
       -7.20292389e-01, -9.11923766e-01, -1.96444058e+00,  6.96357667e-01,
        2.82553196e+00,  8.86794567e-01,  7.77350515e-02,  1.26514721e+00,
        1.51574999e-01,  8.81214917e-01,  7.26933479e-01,  5.30070186e-01,
       -1.04476023e+00, -7.26519585e-01,  6.00238204e-01,  7.08589554e-01,
       -8.04347038e-01,  6.35535002e-01,  4.77252126e-01,  4.82849240e-01,
        1.08375955e+00, -2.08402961e-01, -7.19119728e-01,  1.59578212e-02,
       -1.16444790e+00,  1.34398699e+00,  6.20225847e-01, -5.37892461e-01,
        1.25205851e+00,  1.66239846e+00, -7.21626461e-01, -2.15836930e+00,
       -8.41218352e-01, -3.04035574e-01, -8.90565753e-01,  1.33871138e+00,
       -1.40068817e+00, -9.87447560e-01, -9.18057680e-01, -4.14942652e-02,
       -6.66969538e-01, -4.42624211e-01, -8.24687839e-01, -6.89770222e-01,
       -7.19138622e-01,  8.30125093e-01,  1.50519395e+00,  8.48599792e-01,
       -2.45995140e+00,  4.54199538e-02, -1.07681513e+00, -4.55313742e-01,
       -8.08310986e-01, -2.87792832e-01, -6.75963312e-02, -5.33433855e-02,
        2.81438172e-01, -8.34729075e-01, -3.49502861e-01,  9.37399507e-01,
        1.58218980e+00,  1.08166254e+00, -9.79161024e-01, -1.25616264e+00,
        6.19821548e-01,  7.54942954e-01,  2.38742471e+00, -8.04786384e-01,
        6.20690249e-02,  1.63924265e+00, -3.57281685e-01,  1.24681163e+00,
       -7.04328060e-01,  6.56639814e-01,  1.02607930e+00, -1.90029991e+00,
        8.84660602e-01, -5.51665604e-01,  8.61216187e-01,  1.73704815e+00,
       -6.31164730e-01, -1.92156121e-01,  7.39197671e-01, -9.96906981e-02,
        4.53543723e-01, -2.74722815e-01,  6.35396838e-01,  4.77979630e-01,
       -1.62112033e+00, -4.73908544e-01,  1.54916108e-01,  8.72868672e-02,
        3.51490736e-01,  1.03813183e+00, -6.31477594e-01,  5.78814000e-02,
       -6.81110382e-01, -3.32327217e-01,  1.03429413e+00, -1.19592500e+00,
       -4.12661195e-01,  1.13356280e+00, -5.72262228e-01,  2.52998352e-01,
        4.63825405e-01, -4.39445376e-02,  5.29071152e-01,  1.00338936e+00,
       -1.03138351e+00,  2.01526850e-01, -1.18306208e+00,  2.10764691e-01,
        3.84548232e-02,  7.98298299e-01,  2.57461518e-03, -8.99602890e-01,
       -9.03441250e-01,  2.68376768e-01,  7.63917983e-01, -7.54412338e-02,
       -1.89536884e-01, -9.14447844e-01,  6.49238527e-01, -1.27700651e+00,
        7.50295699e-01,  2.78724313e-01,  2.69981623e-02,  1.08830795e-01,
       -8.64135027e-02, -6.90594316e-01, -5.83201706e-01, -1.72172892e+00,
        1.41299784e-01,  1.38577610e-01, -2.84643471e-02,  5.13906419e-01,
        2.67993689e-01, -2.10930482e-01,  1.46052146e+00,  3.76335531e-01,
        1.18975902e+00, -1.37251806e+00, -1.43176186e+00, -4.86504674e-01,
       -1.50369883e+00,  1.50927043e+00,  8.97010565e-01, -5.28117955e-01,
        7.20376849e-01, -6.94271922e-01,  5.08091688e-01,  3.32407862e-01,
       -1.10095191e+00, -1.23688865e+00,  4.35559392e-01, -8.35498095e-01,
       -6.53884172e-01, -5.74162304e-01,  1.86251891e+00, -1.56217551e+00,
        1.73758721e+00,  1.37841129e+00,  1.18178058e+00, -2.03096604e+00,
       -2.13389564e+00, -5.56552768e-01,  6.19786859e-01, -1.79290092e+00,
        1.66106582e-01,  3.92278135e-01,  3.47218812e-01, -1.17434096e+00,
        1.51897505e-01, -4.70165968e-01,  2.15764165e-01, -2.00690314e-01,
        7.26847887e-01,  7.72878766e-01, -1.81264102e-01, -1.51833296e+00,
        2.01395974e-01, -1.61701787e+00, -2.01473489e-01,  1.44642949e+00,
       -5.62642515e-01, -7.83946991e-01, -5.35178602e-01, -1.65226769e+00,
        1.77601624e+00, -5.24905562e-01, -3.18437994e-01,  1.07273608e-01,
       -8.92303705e-01,  1.40053779e-02, -4.61878449e-01, -1.84299290e-01,
        4.66315508e-01,  1.49042547e+00,  1.97873616e+00, -4.51673716e-01,
       -1.03395140e+00,  6.33082509e-01, -1.04102468e+00, -1.65014243e+00,
       -8.03042769e-01,  1.84256703e-01,  2.49523211e+00, -6.75867200e-01,
        1.45188177e+00, -4.43394631e-01, -5.80608547e-01,  3.26311827e-01,
       -2.11859059e+00, -2.61499405e-01, -9.73938346e-01,  5.37245810e-01,
        5.27569115e-01,  6.16598368e-01, -6.00613892e-01,  1.43442237e+00,
       -7.73577034e-01, -4.48661178e-01,  7.89240837e-01, -2.46398687e-01,
       -3.29280823e-01,  2.73496360e-01,  6.45342648e-01, -6.33711159e-01,
       -8.38444829e-01,  1.86383164e+00,  5.02774775e-01,  7.26007342e-01,
        7.41568983e-01, -9.73917484e-01, -3.45513701e-01,  7.90400088e-01,
       -2.42280498e-01, -1.64721161e-01, -1.80679470e-01,  1.03819644e+00,
        5.05783677e-01, -3.81605268e-01, -2.98180014e-01,  2.33367890e-01,
       -2.36285990e-03, -4.33504343e-01, -6.60190344e-01, -1.47576559e+00,
       -1.49115098e+00, -1.37817204e+00,  4.57122415e-01, -7.49731779e-01,
       -1.82395518e-01, -7.23841608e-01, -1.29406095e-01,  1.80410355e-01,
        1.75216105e-02,  7.06408262e-01,  1.15550369e-01,  6.75940990e-01,
        7.42777348e-01,  7.97802448e-01,  8.20017099e-01, -7.63138711e-01,
        2.31259674e-01,  7.67731667e-01, -2.46530026e-01, -4.97931361e-01,
       -9.75879550e-01,  1.33794248e-02,  6.85923696e-01, -5.66244125e-03,
        1.23502302e+00,  4.86295223e-01,  4.90317866e-02, -3.33507061e-01,
        1.79159570e+00, -2.16586041e+00, -1.96407604e+00,  2.41063833e-01,
        1.06812790e-01, -2.98745520e-02,  3.96790385e-01, -2.74112403e-01,
        1.30779743e-01,  5.51176071e-01,  1.71820849e-01,  1.83801204e-01,
        1.52517366e+00,  5.06723046e-01, -5.11770844e-01,  3.51837188e-01,
        1.05741754e-01,  1.76338637e+00, -2.76448905e-01, -4.56650078e-01,
       -1.08026616e-01, -6.88510984e-02,  1.28079224e+00,  1.35567582e+00,
        1.71081638e+00, -7.83629417e-01,  3.92821044e-01, -3.84556413e-01,
       -4.76336062e-01, -1.83903143e-01,  1.16859114e+00, -3.59645426e-01,
        8.76320720e-01, -5.31223834e-01,  1.38356912e+00,  6.19088888e-01,
        9.25987482e-01,  7.18696952e-01,  1.82479501e+00, -2.14397073e-01,
        7.36876845e-01,  4.68192041e-01,  5.76507390e-01, -5.19523978e-01,
        1.00612020e+00,  1.59483635e+00, -2.37775832e-01, -5.23986578e-01,
        1.33921467e-02, -1.40232578e-01, -3.77912521e-01,  1.09137796e-01,
       -6.28040493e-01, -2.10403111e-02,  2.92693996e+00, -2.68602788e-01,
        9.50957179e-01,  2.03325555e-01, -1.21181238e+00,  8.64352703e-01,
       -3.56349498e-01,  1.26665533e-01,  7.39274740e-01,  3.23421896e-01,
        2.44709179e-02, -7.57467568e-01,  4.59444761e-01, -1.07997134e-01,
        1.11010909e+00,  1.36223286e-01,  1.82294607e+00,  4.49376613e-01,
        9.40604866e-01, -1.69978631e+00, -3.91457379e-01,  6.37428761e-01,
       -1.56802154e+00, -5.70596039e-01, -9.69234943e-01,  9.06360388e-01,
       -4.91270214e-01, -9.38587189e-01, -5.26947439e-01, -6.27766430e-01,
        9.08039570e-01,  1.70320904e+00,  9.78972495e-01,  4.25879866e-01,
       -6.16687417e-01,  1.34997272e+00,  1.06471825e+00, -8.69299889e-01,
        6.33057356e-01, -7.99189627e-01, -1.27741456e+00,  1.73270434e-01,
        3.94638836e-01, -4.11241829e-01, -4.73533362e-01,  6.40477061e-01,
        1.89169794e-01, -7.90874243e-01, -2.42469907e-02,  1.30372632e+00,
       -5.30056238e-01,  7.69588470e-01,  2.41639614e-02,  1.17158204e-01,
       -8.30933332e-01, -1.94041416e-01,  1.53387403e+00, -1.90940320e-01,
        7.12149978e-01, -5.17843843e-01,  1.82411581e-01,  1.26934481e+00,
        5.63395023e-01,  3.48219633e-01, -1.06332111e+00,  1.35051835e+00,
       -1.73458600e+00,  6.07629299e-01,  1.89214587e-01,  2.03246808e+00,
        7.63076186e-01,  2.17721868e+00,  3.34673464e-01,  1.31864011e+00,
        2.10315418e+00,  1.08882356e+00,  1.08983660e+00, -1.32262349e-01,
        1.38277316e+00, -2.49456897e-01,  6.70204699e-01,  6.96321368e-01,
       -6.19291514e-02, -1.25617194e+00, -1.85008287e-01,  1.15262091e-01,
       -1.14538240e+00, -3.45329672e-01,  7.04093695e-01, -4.65359092e-01,
       -1.23566163e+00,  7.43185878e-01, -6.32414281e-01,  8.36467922e-01],
      dtype=float32)

In [16]:
from tqdm.auto import tqdm
import contextlib
import io
import os
import glob
import pandas as pd

embeddings_data = []

for _, row in tqdm(df.iterrows(), total=len(df), desc="Creating embeddings...", dynamic_ncols=True):
    person_name = row['name']
    person_id = row['ID']
    person_path = row['name_path']

    image_paths = glob.glob(os.path.join(person_path, '*.jpg'))

    for img_path in image_paths:
        try:
            with contextlib.redirect_stdout(io.StringIO()), contextlib.redirect_stderr(io.StringIO()):
                embedding = img_to_embedding(img_path)

            if embedding is None:
                continue

            embeddings_data.append({
                'name': person_name,
                'ID': person_id,
                'embedding': embedding,
                'embedding type': type(embedding),
                'embedding dtype': embedding.dtype,
                'embedding_size': embedding.size,
                'image_name': os.path.basename(img_path),
                'filepath': img_path
            })

        except Exception as e:
            tqdm.write(f"❌ Error on image: {img_path} | {e}")

/home/sho/anaconda3/envs/face-gen-notebook/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Creating embeddings...: 100%|██████████| 5749/5749 [5:18:25<00:00,  3.32s/it]

In [ ]:
"""embeddings_data = []

for _, row in tqdm(df.iterrows(), total=len(df), desc="creating embeddings..."):
    person_name = row['name']
    person_id = row['ID']
    person_path = row['name_path']
    
    # Find all jpg images in this person's folder
    image_paths = glob.glob(os.path.join(person_path, '*.jpg'))
    
    for img_path in image_paths:
        embedding = img_to_embedding(img_path)
        if embedding is None:
            continue
        
        embeddings_data.append({
            'name': person_name,
            'ID': person_id,
            'embedding': embedding, 
            'embedding type': type(embedding),
            'embedding dtype': embedding.dtype,
            'embedding_size': embedding.size, 
            'image_name': os.path.basename(img_path),
            'filepath': img_path
        })"""

ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html

In [14]:
df_embeddings = pd.DataFrame(embeddings_data)
df_embeddings.shape
df_embeddings.head()

,name,ID,embedding,embedding type,embedding dtype,embedding_size,image_name,filepath
0,AJ_Cook,0,"[-0.3419863, 0.6712041, -1.2866051, 0.60350394...",<class 'numpy.ndarray'>,float32,512,AJ_Cook_0001.jpg,/home/sho/Insightface-Face-Recognition/img/LFW...
1,AJ_Lamas,1,"[0.059667192, 0.076293096, 1.3340704, 1.245711...",<class 'numpy.ndarray'>,float32,512,AJ_Lamas_0001.jpg,/home/sho/Insightface-Face-Recognition/img/LFW...
2,Aaron_Eckhart,2,"[1.2447274, -0.9747005, 1.2987878, 0.46920043,...",<class 'numpy.ndarray'>,float32,512,Aaron_Eckhart_0001.jpg,/home/sho/Insightface-Face-Recognition/img/LFW...
3,Aaron_Guiel,3,"[-0.17151171, -1.2514898, -0.38039768, -0.0818...",<class 'numpy.ndarray'>,float32,512,Aaron_Guiel_0001.jpg,/home/sho/Insightface-Face-Recognition/img/LFW...
4,Aaron_Patterson,4,"[0.41729146, -0.24729499, -0.86146384, -2.1820...",<class 'numpy.ndarray'>,float32,512,Aaron_Patterson_0001.jpg,/home/sho/Insightface-Face-Recognition/img/LFW...

In [20]:
df_embeddings = pd.DataFrame(embeddings_data)
print(df_embeddings.shape)
df_embeddings.head()
df_embeddings.to_csv("./embeddings.csv", index=False)

(13195, 8)

In [2]:
import pandas as pd

In [4]:
# reload embeddings df
df_emb = pd.read_csv("./embeddings.csv")
df_emb.shape

(13195, 8)

In [4]:
df_emb.head()

,name,ID,embedding,embedding type,embedding dtype,embedding_size,image_name,filepath
0,AJ_Cook,0,[-3.41986299e-01 6.71204090e-01 -1.28660512e+...,<class 'numpy.ndarray'>,float32,512,AJ_Cook_0001.jpg,/home/sho/Insightface-Face-Recognition/img/LFW...
1,AJ_Lamas,1,[ 5.96671924e-02 7.62930959e-02 1.33407044e+...,<class 'numpy.ndarray'>,float32,512,AJ_Lamas_0001.jpg,/home/sho/Insightface-Face-Recognition/img/LFW...
2,Aaron_Eckhart,2,[ 1.24472737e+00 -9.74700511e-01 1.29878783e+...,<class 'numpy.ndarray'>,float32,512,Aaron_Eckhart_0001.jpg,/home/sho/Insightface-Face-Recognition/img/LFW...
3,Aaron_Guiel,3,[-0.17151171 -1.2514898 -0.38039768 -0.081882...,<class 'numpy.ndarray'>,float32,512,Aaron_Guiel_0001.jpg,/home/sho/Insightface-Face-Recognition/img/LFW...
4,Aaron_Patterson,4,[ 0.41729146 -0.24729499 -0.86146384 -2.182007...,<class 'numpy.ndarray'>,float32,512,Aaron_Patterson_0001.jpg,/home/sho/Insightface-Face-Recognition/img/LFW...

In [10]:
type(df_emb.embedding[0])

str

In [11]:
df_emb.embedding[0]

'[-3.41986299e-01  6.71204090e-01 -1.28660512e+00  6.03503942e-01\n -3.18364918e-01 -4.68093991e-01 -2.34770045e-01  3.22836861e-02\n  7.13358521e-01 -6.83606386e-01 -6.01341248e-01 -2.26560807e+00\n  1.31078124e+00  1.09312689e+00  5.34345269e-01  1.09747398e+00\n -4.83847260e-01 -2.11912215e-01 -2.36376584e-01 -3.22396383e-02\n  2.48618588e-01 -1.68814075e+00 -1.91167235e+00  4.39560950e-01\n  4.66680527e-01 -5.63056290e-01  8.96633506e-01  1.81865704e+00\n  6.78355932e-01 -1.46311998e+00 -1.45712420e-01 -7.37816811e-01\n  9.33966041e-01  4.59790051e-01  5.24055779e-01 -3.94828200e-01\n -1.12502050e+00 -7.19395816e-01 -9.17202830e-01 -4.87413019e-01\n  1.40539682e+00  1.25581741e-01 -8.22785020e-01 -7.52641618e-01\n  5.46758711e-01 -6.08044565e-01  2.52439946e-01  4.20660019e-01\n  6.25930011e-01  5.21705449e-01 -1.10720861e+00  7.13488579e-01\n -8.57424736e-01  6.78034306e-01  9.67450202e-01  1.18356633e+00\n  5.84251583e-01  6.37974858e-01  1.24099672e-01 -1.52626216e+00\n  1.64706767e-01 -7.56314397e-01  1.12926483e+00 -5.26633561e-01\n  4.41167653e-01  4.41189483e-02 -3.41944069e-01 -1.19594419e+00\n  1.53841352e+00  7.65169919e-01 -1.47572851e+00  6.62295640e-01\n  1.24950337e+00  1.34657526e+00  7.00815022e-02 -2.56579071e-01\n -1.94999620e-01 -2.47383177e-01  1.79906249e-01  7.38886952e-01\n -4.16763574e-02 -1.52798331e+00 -8.78770888e-01 -6.69042468e-01\n  1.18932521e+00  1.61862999e-01  1.37701094e-01 -4.60591465e-02\n  8.01709473e-01 -1.48927748e+00 -1.60825849e-01 -1.42231023e+00\n  1.41605973e+00  1.76699221e-01  1.95959032e-01  1.67377162e+00\n  9.00534928e-01 -1.36515868e+00 -1.09631741e+00  1.40168440e+00\n  7.99511015e-01  2.50899100e+00  3.61318141e-01  1.14547610e+00\n  1.20762444e+00 -4.22910154e-01  9.34149504e-01  1.19665170e+00\n -8.29214677e-02 -9.38297868e-01 -9.51716542e-01 -1.46424741e-01\n -2.65358353e+00 -5.56915879e-01 -6.34672582e-01 -1.53327549e+00\n  7.72367477e-01  5.67458868e-01  5.58740258e-01  6.21342301e-01\n -1.21701467e+00  2.66825527e-01 -1.56500375e+00 -6.22416496e-01\n  2.32142538e-01  2.09874399e-02 -9.75496352e-01 -2.58313715e-01\n  1.70652997e+00 -2.69575924e-01 -7.27335155e-01 -6.63482398e-02\n  4.67494845e-01 -8.46725106e-01  5.40497839e-01  2.64015198e-01\n -2.47244447e-01 -6.84724033e-01  6.45512462e-01 -3.52293640e-01\n  1.09537768e+00 -5.55513620e-01 -4.77364779e-01  2.13393196e-01\n -1.00560367e+00 -3.80465865e-01  1.06402850e+00  1.32413733e+00\n -4.75676686e-01  1.55181813e+00  1.15495050e+00  3.55952293e-01\n -2.62671411e-01  3.35853040e-01  3.41771603e-01  1.65244579e+00\n  1.17625964e+00  4.95605111e-01 -7.69879043e-01  9.18615222e-01\n  7.22885787e-01  8.98020148e-01 -9.05978382e-01  1.55369651e+00\n -5.69137216e-01  6.70489311e-01  5.39794683e-01 -1.28110456e+00\n -1.32898659e-01  9.30243790e-01  8.15524876e-01  9.29498255e-01\n -1.07314043e-01 -3.27686012e-01  2.08683997e-01 -1.29033422e+00\n -4.30006742e-01 -1.73106909e+00 -2.00698280e+00 -3.36988330e-01\n -5.79326332e-01 -5.31993032e-01 -4.99842390e-02 -9.56296921e-04\n  1.56967789e-01  3.01077902e-01  1.09156704e+00 -1.12743962e+00\n  1.83535802e+00  1.45230687e+00 -1.47408426e+00 -3.96545708e-01\n  5.69331944e-02 -4.19301271e-01 -1.79656088e-01  4.14414525e-01\n  1.57338440e+00 -7.70961046e-01  1.24122405e+00  1.67018867e+00\n  1.07614040e+00  2.00367999e+00  1.05120611e+00  7.56131053e-01\n -3.25983353e-02 -1.84343708e+00  3.35665107e-01 -4.26816374e-01\n  8.21950316e-01  4.25997883e-01  4.53969836e-02 -1.81081176e+00\n -1.56445384e+00  5.63511923e-02 -8.78959373e-02 -1.07945597e+00\n -1.53501302e-01  3.77429128e-01  9.88322854e-01  2.63691753e-01\n -9.21829939e-02  6.06563017e-02  8.78982246e-01  1.41391575e-01\n  4.63729620e-01  1.00653306e-01  1.00879359e+00 -3.22864875e-02\n  4.64959890e-02 -3.43271375e-01 -1.46272647e+00  1.75991571e+00\n  8.68241251e-01  6.61005497e-01 -9.58924651e-01  6.92858815e-01\n -1.51764476e+00 -6.07473731e-01 -1.77793637e-01 -5.40570259e-01\n -7.16952145e-01 -1.62663087e-01  4.50169563e-01 -6.14940941e-01\n  8.55763793e-01  1.05373836e+00  2.55194455e-02 -1.11225843e+00\n -2.63746530e-02 -5.77986956e-01  1.61529791e+00  1.17194378e+00\n -4.21776474e-01 -6.78818047e-01 -8.46074164e-01 -1.97471812e-01\n -1.07192636e+00 -1.51386964e+00 -9.43316042e-01 -7.85753131e-04\n  1.28290105e+00  5.42295218e-01  1.45414591e+00  6.36655807e-01\n  1.33651531e+00  1.57726264e+00  3.00599813e-01  2.20785475e+00\n -9.00209844e-02  6.34367824e-01  1.07853520e+00 -3.90927225e-01\n -5.58909103e-02 -1.75848770e+00  1.61425248e-01  2.60266274e-01\n  4.93603200e-03 -1.64655805e-01  1.50211513e-01 -1.14353037e+00\n -7.99257934e-01 -1.32020086e-01  9.21047390e-01  8.15405190e-01\n  1.71449745e+00 -4.96331692e-01 -3.51164162e-01  1.25303268e-02\n  6.57907486e-01 -8.57879758e-01 -7.23872662e-01  2.72560805e-01\n  4.79124904e-01 -5.25174737e-01 -1.87938422e-01  1.37777090e-01\n -2.77844369e-02  3.52478623e-02  3.19628865e-01 -3.31556976e-01\n  3.62641633e-01 -3.09605002e-02  1.73574507e+00  1.24742103e+00\n -8.85308743e-01  1.00079560e+00  1.32824028e+00  3.23497653e-01\n  1.38639045e+00  2.77193010e-01 -2.06971073e+00  9.56731588e-02\n -4.03909773e-01  3.28347772e-01  9.73844349e-01  1.23220181e+00\n  6.81546271e-01 -4.72802073e-01 -2.00160241e+00  1.08380640e+00\n  6.06414855e-01  7.45915771e-02  7.68063962e-01  2.33428732e-01\n -5.90280443e-03  6.56151414e-01 -1.37343332e-02 -1.60492277e+00\n -5.25920868e-01  3.54543388e-01 -2.52278566e+00 -1.62404507e-01\n  6.99333325e-02  6.75365806e-01 -1.66666090e+00 -4.68902558e-01\n  1.24686050e+00 -5.28324723e-01  4.12907809e-01  1.18019438e+00\n -6.81716204e-01 -6.09712481e-01  1.54939806e+00 -1.64777145e-01\n  1.71332383e+00 -2.73063004e-01  1.88163757e-01 -2.18832731e+00\n -2.69435287e-01 -7.74300545e-02  3.92302155e-01  4.89464581e-01\n  4.41819191e-01  6.82958663e-02 -2.18773559e-01  8.46801579e-01\n  1.97622037e+00  4.56357121e-01 -4.98954058e-01  1.21433660e-01\n -8.04543972e-01 -1.37963951e-01 -1.91327882e+00  6.90229058e-01\n -4.60056126e-01  1.19872427e+00  4.81478095e-01 -9.16904807e-02\n -4.37928066e-02 -2.40617380e-01  2.35887527e-01 -2.81931221e-01\n  1.04462850e+00 -1.39040208e+00 -3.12103033e-01 -3.86627048e-01\n -3.27881664e-01  9.31562603e-01  1.00441420e+00  3.64192188e-01\n  1.35245705e+00  4.47624415e-01  1.98952925e+00  1.48755586e+00\n -6.84529781e-01  5.90580046e-01 -5.46055794e-01  7.38555312e-01\n  3.34049016e-02 -8.64107668e-01  2.01154017e+00 -1.69063067e+00\n -8.01657438e-01 -7.56621242e-01  4.87318009e-01  8.33834410e-01\n -6.93731844e-01  2.94314712e-01  1.24114001e+00  1.52988315e+00\n -2.59811401e-01  1.57285500e+00 -1.23103845e+00 -1.29131806e+00\n -4.33689266e-01  1.55138731e-01 -1.86429098e-01  4.63609457e-01\n  1.00260103e+00  9.17722702e-01  1.29612505e+00  5.68884373e-01\n  1.36238527e+00 -8.00492644e-01 -7.47410476e-01 -6.69582129e-01\n  2.86807537e-01  1.93402737e-01 -1.82641816e+00 -1.11805332e+00\n -2.20740348e-01  1.42187023e+00 -9.87687588e-01  3.78793210e-01\n -9.23126459e-01  2.53163129e-02 -7.29539335e-01 -8.53275061e-01\n -9.43471074e-01 -7.27889240e-01  9.74629223e-02  9.96386290e-01\n  1.07031572e+00  7.39854932e-01  1.12495005e-01 -6.88322544e-01\n -1.06772184e+00 -4.25222099e-01 -6.10181510e-01 -2.32161856e+00\n  3.50869119e-01  4.43163455e-01  1.75718606e-01 -1.13462222e+00\n -1.08907819e+00 -2.85020143e-01  1.37383723e+00 -1.22038102e+00\n -6.14305854e-01 -6.84289575e-01  1.10771966e+00 -2.58053958e-01\n  3.93288881e-01  5.53340793e-01 -9.79704320e-01 -1.26857269e+00\n  4.04583290e-04  1.49762183e-01 -1.18037844e+00  8.26628923e-01\n  1.26936913e+00  1.32707417e-01  3.39098901e-01 -3.93249914e-02\n  9.99074817e-01 -2.19948068e-01 -9.16704953e-01 -1.24049388e-01\n  5.26664555e-01  2.21906751e-01 -5.87400198e-02  8.49416181e-02\n -2.26040864e+00 -6.88265204e-01  1.97286531e-02 -1.54544127e+00\n  3.53967428e-01 -1.15218990e-01 -1.35447755e-01 -3.83093208e-03\n  1.08527815e+00  7.91073084e-01 -1.22519612e+00  1.22995421e-01\n  1.57613695e-01 -1.38617516e+00  7.41208196e-01 -1.35802403e-01\n -2.57013828e-01 -1.14681149e+00  8.48400414e-01  8.54625642e-01\n -3.24156098e-02 -1.33515906e+00  5.17241433e-02  1.94580245e+00\n -9.88638341e-01  1.57495871e-01 -1.54320288e+00 -1.15375865e+00\n -7.50134349e-01  1.40929413e+00  4.19578046e-01 -2.26352477e+00\n -4.16327775e-01 -2.16598463e+00 -2.69082427e-01  2.16478594e-02\n -1.51476824e+00  1.25850797e+00 -1.21980619e+00 -7.44213998e-01]'

In [14]:
# convert csv to pkl
df = pd.read_csv("./embeddings.csv")

import ast
import numpy as np

df['embedding'] = df['embedding'].apply(
    lambda x: np.fromstring(x.strip('[]'), sep=' ')
)
#df['embedding'] = df['embedding'].apply(lambda x: np.array(ast.literal_eval(x)))

# Save it as a Pickle file
df.to_pickle("./embeddings-0312.pkl")

# start here

In [1]:
import pandas as pd
import numpy as np
from tqdm.auto import tqdm
import insightface

In [2]:
df = pd.read_pickle("./embeddings-0312.pkl")

print(type(df['embedding'].iloc[0]))  # <class 'numpy.ndarray'>
is_array_col = df['embedding'].apply(lambda x: isinstance(x, np.ndarray))
print(is_array_col.value_counts())

# convert back to float32
df['embedding'] = df['embedding'].apply(lambda x: x.astype(np.float32))

<class 'numpy.ndarray'>
embedding
True    13195
Name: count, dtype: int64

In [3]:
df['embedding'].iloc[0].dtype

dtype('float32')

# sanity check

In [ ]:
import random

detector = insightface.model_zoo.get_model('/home/sho/.insightface/models/buffalo_l/w600k_r50.onnx')
#app = FaceAnalysis()

# Select a random embedding
query_idx = random.randint(0, len(df) - 1)
query_emb = df['embedding'].iloc[query_idx]

similarities = []

for i in tqdm(range(len(df)), desc="Searching similar embeddings", dynamic_ncols=True):
    emb = df['embedding'].iloc[i]
    sim = detector.compute_sim(query_emb, emb)
    #print(f'Similarity score: {sim}')
    similarities.append(sim)

# Find top match
top_match_idx = np.argmax(similarities)

print(f"Query index: {query_idx}")
print(f"Top match index: {top_match_idx}")
print(f"Similarity score: {similarities[top_match_idx]:.6f}")

/home/sho/anaconda3/envs/face-gen-notebook/lib/python3.13/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py:118: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(

Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}

Searching similar embeddings:   0%|          | 0/13195 [00:00<?, ?it/s]

Similarity score: -0.07656122744083405
Similarity score: -0.0196909811347723
Similarity score: 0.10059366375207901
Similarity score: -0.045011185109615326
Similarity score: -0.08891334384679794
Similarity score: -0.008606958203017712
Similarity score: -0.037452057003974915
Similarity score: -0.05270988121628761
Similarity score: 0.00015827461902517825
Similarity score: -0.08940943330526352
Similarity score: -0.0745629221200943
Similarity score: -0.05183979123830795
Similarity score: -0.0893077403306961
Similarity score: 0.10029501467943192
Similarity score: -0.02859790436923504
Similarity score: 0.0018946267664432526
Similarity score: -0.07020122557878494
Similarity score: -0.03331659734249115
Similarity score: -0.07494957745075226
Similarity score: -0.005163185298442841
Similarity score: -0.033646076917648315
Similarity score: -0.028748519718647003
Similarity score: 0.014923726208508015
Similarity score: -0.05421985313296318
Similarity score: -0.027627335861325264
Similarity score: -0.0140047837048769
Similarity score: 0.03056253120303154
Similarity score: -0.0029938099905848503
Similarity score: 0.01224054116755724
Similarity score: 0.003943287301808596
Similarity score: -0.13791286945343018
Similarity score: -0.06522468477487564
Similarity score: -0.11944580078125
Similarity score: 0.014707917347550392
Similarity score: -0.09257776290178299
Similarity score: -0.04981587454676628
Similarity score: -0.026604972779750824
Similarity score: -0.04329827427864075
Similarity score: -0.05861249566078186
Similarity score: -0.03616083413362503
Similarity score: -0.04452693089842796
Similarity score: -0.07560445368289948
Similarity score: -0.0577038936316967
Similarity score: -0.0887710303068161
Similarity score: -0.044679831713438034
Similarity score: -0.011418196372687817
Similarity score: -0.07146205753087997
Similarity score: -0.10380449891090393
Similarity score: -0.04372357577085495
Similarity score: -0.10024448484182358
Similarity score: -0.035044293850660324
Similarity score: -0.09583525359630585
Similarity score: -0.10468854755163193
Similarity score: -0.12579315900802612
Similarity score: -0.09474067389965057
Similarity score: -0.057326607406139374
Similarity score: -0.021300900727510452
Similarity score: -0.0007328796782530844
Similarity score: -0.08057950437068939
Similarity score: 0.02085544914007187
Similarity score: 0.0171754602342844
Similarity score: 0.04797932878136635
Similarity score: 0.09790748357772827
Similarity score: 0.1119234561920166
Similarity score: 0.08804546296596527
Similarity score: -0.012598050758242607
Similarity score: 0.00942656397819519
Similarity score: 0.07817442715167999
Similarity score: 0.036679334938526154
Similarity score: 0.07836547493934631
Similarity score: -0.04954030364751816
Similarity score: 0.026595618575811386
Similarity score: 0.05268936976790428
Similarity score: 0.19693008065223694
Similarity score: 0.11869838088750839
Similarity score: 0.0999600812792778
Similarity score: 0.1029447540640831
Similarity score: 0.052315257489681244
Similarity score: 0.006957072764635086
Similarity score: 0.0067804716527462006
Similarity score: 0.01671925187110901
Similarity score: -0.01201327983289957
Similarity score: -0.029681328684091568
Similarity score: 0.029419463127851486
Similarity score: 0.1006048321723938
Similarity score: 0.03891065716743469
Similarity score: 0.021318934857845306
Similarity score: 0.19962050020694733
Similarity score: 0.2222929745912552
Similarity score: 0.041643306612968445
Similarity score: 0.0068745543248951435
Similarity score: 0.018612859770655632
Similarity score: 0.050566162914037704
Similarity score: -0.0013669313630089164
Similarity score: 0.0818820670247078
Similarity score: -0.041864246129989624
Similarity score: -0.07517800480127335
Similarity score: -0.023820899426937103
Similarity score: 0.023050395771861076
Similarity score: -0.01991262473165989
Similarity score: -0.0186136607080698
Similarity score: -0.05147895961999893
Similarity score: -0.056702870875597
Similarity score: -0.029630599543452263
Similarity score: -0.07236922532320023
Similarity score: -0.04587484896183014
Similarity score: 0.01876254193484783
Similarity score: -0.009560616686940193
Similarity score: -0.057760339230298996
Similarity score: -0.07616791874170303
Similarity score: 0.001602271804586053
Similarity score: -0.07612008601427078
Similarity score: -0.04827200993895531
Similarity score: 0.020369073376059532
Similarity score: -0.09144385904073715
Similarity score: 0.11939835548400879
Similarity score: 0.034173958003520966
Similarity score: 0.06887491792440414
Similarity score: 0.05692978575825691
Similarity score: 0.0930468738079071
Similarity score: -0.07082246989011765
Similarity score: -0.07437126338481903
Similarity score: -0.02088836207985878
Similarity score: -0.08232729136943817
Similarity score: -0.03915158286690712
Similarity score: 0.05595199391245842
Similarity score: 0.04691869392991066
Similarity score: -0.003846764098852873
Similarity score: 0.07805834710597992
Similarity score: -0.04073008894920349
Similarity score: -0.07280503213405609
Similarity score: -0.015227328054606915
Similarity score: 0.042645785957574844
Similarity score: -0.04678754135966301
Similarity score: -0.004792219493538141
Similarity score: -0.021023601293563843
Similarity score: 0.016827717423439026
Similarity score: -0.03665521740913391
Similarity score: -0.0660417452454567
Similarity score: -0.07354489713907242
Similarity score: -0.004679200705140829
Similarity score: 0.034133851528167725
Similarity score: -0.07120664417743683
Similarity score: 0.1237090453505516
Similarity score: -0.04289967566728592
Similarity score: 0.12095259130001068
Similarity score: 0.12900476157665253
Similarity score: 0.0010321206646040082
Similarity score: -0.12359751760959625
Similarity score: -0.04990328848361969
Similarity score: -0.03720102831721306
Similarity score: -0.07161770015954971
Similarity score: -0.06862343102693558
Similarity score: 0.08398207277059555
Similarity score: 0.09145914018154144
Similarity score: 0.017528899013996124
Similarity score: 0.03040674701333046
Similarity score: -0.07259267568588257
Similarity score: -0.010102233849465847
Similarity score: 0.09284581243991852
Similarity score: -0.035922639071941376
Similarity score: -0.09060943871736526
Similarity score: -0.049665458500385284
Similarity score: -0.0705643817782402
Similarity score: -0.050676971673965454
Similarity score: -0.06502566486597061
Similarity score: -0.08595120906829834
Similarity score: -0.0050757029093801975
Similarity score: -0.026989394798874855
Similarity score: 0.07240691781044006
Similarity score: 0.004170568194240332
Similarity score: -0.013300320133566856
Similarity score: -0.0033666633535176516
Similarity score: 0.012696918100118637
Similarity score: 0.011519020423293114
Similarity score: 0.007417560555040836
Similarity score: 0.06993567198514938
Similarity score: 0.03480149805545807
Similarity score: 0.0201906468719244
Similarity score: 0.06200921908020973
Similarity score: -0.019501889124512672
Similarity score: -0.026077665388584137
Similarity score: 0.0564018115401268
Similarity score: 0.06893204152584076
Similarity score: 0.048108696937561035
Similarity score: -0.05420077219605446
Similarity score: -0.013689616695046425
Similarity score: 0.04949214681982994
Similarity score: 0.01935158669948578
Similarity score: 0.00610863883048296
Similarity score: 0.020959096029400826
Similarity score: 0.11422159522771835
Similarity score: -0.06615874171257019
Similarity score: 0.07260601967573166
Similarity score: 0.05326244607567787
Similarity score: -0.09625472128391266
Similarity score: 0.05425122380256653
Similarity score: -0.05303462594747543
Similarity score: -0.055570732802152634
Similarity score: 0.06988951563835144
Similarity score: 0.013998068869113922
Similarity score: 3.0005610824446194e-05
Similarity score: 0.011342210695147514
Similarity score: -0.02417822740972042
Similarity score: 0.0367981418967247
Similarity score: -0.02620110847055912
Similarity score: 0.15220189094543457
Similarity score: 0.001948893303051591
Similarity score: -0.07968160510063171
Similarity score: 0.04502144083380699
Similarity score: 0.016108708456158638
Similarity score: 0.020258072763681412
Similarity score: 0.03258924558758736
Similarity score: 0.006988099310547113
Similarity score: -0.009274100884795189
Similarity score: 0.025906099006533623
Similarity score: 0.004514691885560751
Similarity score: -0.04128880798816681
Similarity score: -0.05384740233421326
Similarity score: 0.07248795032501221
Similarity score: 0.10143385827541351
Similarity score: -0.028097078204154968
Similarity score: 0.040534306317567825
Similarity score: 0.02964053489267826
Similarity score: 0.06787603348493576
Similarity score: 0.029929203912615776
Similarity score: 0.042408157140016556
Similarity score: -0.013012159615755081
Similarity score: 0.08062834292650223
Similarity score: -0.03335285559296608
Similarity score: -0.051656510680913925
Similarity score: 0.004969799425452948
Similarity score: -0.003056754358112812
Similarity score: 0.034011296927928925
Similarity score: 0.06644326448440552
Similarity score: 0.02570868469774723
Similarity score: -0.05310399830341339
Similarity score: 0.05160791054368019
Similarity score: -0.001633228501304984
Similarity score: 0.07093226164579391
Similarity score: 0.07874438166618347
Similarity score: 0.0512973852455616
Similarity score: 0.0677894875407219
Similarity score: -0.04090619459748268
Similarity score: -0.012014723382890224
Similarity score: 0.04998112469911575
Similarity score: 0.08028028905391693
Similarity score: -0.02391458861529827
Similarity score: 0.0376293882727623
Similarity score: 0.030833978205919266
Similarity score: 0.014556399546563625
Similarity score: 0.01471114531159401
Similarity score: 0.013093681074678898
Similarity score: 0.034845758229494095
Similarity score: -0.025304758921265602
Similarity score: 0.05542962625622749
Similarity score: 0.011233420111238956
Similarity score: -0.013936179690063
Similarity score: 0.026195574551820755
Similarity score: -0.02425265498459339
Similarity score: 0.013119073584675789
Similarity score: 0.08671547472476959
Similarity score: 0.07128654420375824
Similarity score: 0.0458458736538887
Similarity score: -0.006235575769096613
Similarity score: 0.028464771807193756
Similarity score: 0.05863415449857712
Similarity score: 0.02008269540965557
Similarity score: -0.03949267044663429
Similarity score: 0.035160716623067856
Similarity score: 0.0068267276510596275
Similarity score: 0.05989158898591995
Similarity score: 0.07521703094244003
Similarity score: 0.08482159674167633
Similarity score: 0.047810133546590805
Similarity score: 0.061843063682317734
Similarity score: 0.057440076023340225
Similarity score: 0.07449875771999359
Similarity score: 0.03227049112319946
Similarity score: 0.06539002060890198
Similarity score: 0.0484091117978096
Similarity score: 0.032482217997312546
Similarity score: 0.08508844673633575
Similarity score: -0.07505954802036285
Similarity score: -0.015999864786863327
Similarity score: -0.009242396801710129
Similarity score: -0.048525672405958176
Similarity score: -0.013462820090353489
Similarity score: -0.15369287133216858
Similarity score: 0.04694000259041786
Similarity score: -0.06944148987531662
Similarity score: -0.0708506777882576
Similarity score: 0.04049737751483917
Similarity score: -0.1218639463186264
Similarity score: 0.02641340345144272
Similarity score: 0.005019259639084339
Similarity score: 0.07587902247905731
Similarity score: 0.019202208146452904
Similarity score: 0.0411263108253479
Similarity score: 0.041845373809337616
Similarity score: -0.026946764439344406
Similarity score: -0.04317111521959305
Similarity score: -0.03388720750808716
Similarity score: -0.04945817217230797
Similarity score: -0.10477692633867264
Similarity score: -0.10149695724248886
Similarity score: 0.06982884556055069
Similarity score: -0.06257601827383041
Similarity score: -0.042702410370111465
Similarity score: -0.05794418603181839
Similarity score: -0.004188062623143196
Similarity score: 0.031546495854854584
Similarity score: -0.012700612656772137
Similarity score: 0.10028426349163055
Similarity score: 0.003477725898846984
Similarity score: 0.05744483321905136
Similarity score: 0.005635859444737434
Similarity score: -0.007150125689804554
Similarity score: -0.02752111107110977
Similarity score: 0.06889185309410095
Similarity score: 0.04998842626810074
Similarity score: 0.05386681482195854
Similarity score: -0.004932296462357044
Similarity score: -0.038162004202604294
Similarity score: -0.048049911856651306
Similarity score: 0.11094845831394196
Similarity score: 0.10940060019493103
Similarity score: 0.09956567734479904
Similarity score: 0.04324450343847275
Similarity score: 0.028284268453717232
Similarity score: -0.02199321612715721
Similarity score: -0.01783420518040657
Similarity score: -0.052297547459602356
Similarity score: 0.026583079248666763
Similarity score: 6.420956924557686e-05
Similarity score: 0.01768093928694725
Similarity score: 0.023209508508443832
Similarity score: -0.04951856657862663
Similarity score: 0.0232866033911705
Similarity score: -0.024504367262125015
Similarity score: 0.03172922134399414
Similarity score: 0.004739923402667046
Similarity score: -0.06740722805261612
Similarity score: -0.014056801795959473
Similarity score: 0.04173777624964714
Similarity score: -0.004731305874884129
Similarity score: -0.048327092081308365
Similarity score: 0.011434467509388924
Similarity score: 0.05873439833521843
Similarity score: 0.11393222957849503
Similarity score: 0.0020485527347773314
Similarity score: -0.03398899734020233
Similarity score: -0.021748598664999008
Similarity score: -0.02057926543056965
Similarity score: 0.026984557509422302
Similarity score: 0.025153765454888344
Similarity score: 0.025655599310994148
Similarity score: -0.11966967582702637
Similarity score: -0.043579671531915665
Similarity score: -0.0527723953127861
Similarity score: -0.0736401230096817
Similarity score: -0.07851484417915344
Similarity score: -0.06631599366664886
Similarity score: -0.07856496423482895
Similarity score: -0.09637734293937683
Similarity score: -0.008492178283631802
Similarity score: -0.053572267293930054
Similarity score: 0.018983177840709686
Similarity score: 0.012307548895478249
Similarity score: 0.09524934738874435
Similarity score: -0.02012256719172001
Similarity score: -0.08930248022079468
Similarity score: 0.03392159938812256
Similarity score: -0.032602205872535706
Similarity score: 0.01377284899353981
Similarity score: -0.0739176794886589
Similarity score: -0.021403560414910316
Similarity score: -0.06532963365316391
Similarity score: 0.010809135623276234
Similarity score: 0.021175704896450043
Similarity score: 0.029180772602558136
Similarity score: 0.10411691665649414
Similarity score: 0.028572630137205124
Similarity score: 0.011339504271745682
Similarity score: 0.00734143890440464
Similarity score: -0.044148996472358704
Similarity score: -0.02307179570198059
Similarity score: -0.008707706816494465
Similarity score: 0.008922094479203224
Similarity score: -0.03173757717013359
Similarity score: -0.02975773625075817
Similarity score: 0.03540665656328201
Similarity score: -0.043527405709028244
Similarity score: -0.04575599730014801
Similarity score: 0.02383553981781006
Similarity score: -0.014530506916344166
Similarity score: 0.030405575409531593
Similarity score: -0.059276334941387177
Similarity score: -0.08138008415699005
Similarity score: 0.018093720078468323
Similarity score: 0.01919803023338318
Similarity score: 0.08011335879564285
Similarity score: 0.0720779150724411
Similarity score: -0.053367700427770615
Similarity score: -0.061990607529878616
Similarity score: 0.01173850242048502
Similarity score: -0.12997739017009735
Similarity score: -0.03127162531018257
Similarity score: -0.052892301231622696
Similarity score: -0.004622261505573988
Similarity score: -0.04740166291594505
Similarity score: -0.0009428426856175065
Similarity score: 0.021777186542749405
Similarity score: -0.0039027605671435595
Similarity score: -0.07739734649658203
Similarity score: 0.052419159561395645
Similarity score: 0.0011306701926514506
Similarity score: 0.03040071204304695
Similarity score: 0.020835453644394875
Similarity score: 0.01965208165347576
Similarity score: -0.02058742754161358
Similarity score: 0.051076751202344894
Similarity score: 0.007421708200126886
Similarity score: 0.026115132495760918
Similarity score: -0.0008941497071646154
Similarity score: 0.02951194904744625
Similarity score: -0.058864906430244446
Similarity score: 0.0245242677628994
Similarity score: 0.0020792733412235975
Similarity score: 0.03433416411280632
Similarity score: 0.070001982152462
Similarity score: -0.03123263455927372
Similarity score: 0.03489529341459274
Similarity score: -0.03070545196533203
Similarity score: -0.03749893978238106
Similarity score: 0.05697266012430191
Similarity score: 0.052428655326366425
Similarity score: 0.11113840341567993
Similarity score: 0.019202079623937607
Similarity score: -0.02355179935693741
Similarity score: 0.022462597116827965
Similarity score: -0.0025936586316674948
Similarity score: -0.007942470721900463
Similarity score: 0.06805139780044556
Similarity score: 0.0019192122854292393
Similarity score: 0.03853864222764969
Similarity score: 0.037901971489191055
Similarity score: 0.05574990436434746
Similarity score: 0.05314299836754799
Similarity score: -0.004142869263887405
Similarity score: 0.08131872862577438
Similarity score: -0.015469526872038841
Similarity score: 0.007423703558743
Similarity score: 0.012286344543099403
Similarity score: -0.050092991441488266
Similarity score: -0.014780625700950623
Similarity score: 0.04759901389479637
Similarity score: -0.02390691451728344
Similarity score: -0.0801045298576355
Similarity score: -0.005135559942573309
Similarity score: -0.08155117183923721
Similarity score: -0.06028185039758682
Similarity score: -0.003430284559726715
Similarity score: -0.0480087585747242
Similarity score: 0.014232298359274864
Similarity score: -0.016625531017780304
Similarity score: -0.07220947742462158
Similarity score: -0.03448990732431412
Similarity score: 0.004883543122559786
Similarity score: -0.024779116734862328
Similarity score: -0.04086083918809891
Similarity score: -0.056899748742580414
Similarity score: -0.06280529499053955
Similarity score: 0.007335383910685778
Similarity score: -0.07863522320985794
Similarity score: -0.021984076127409935
Similarity score: -0.07410264760255814
Similarity score: -0.09896981716156006
Similarity score: -0.09518774598836899
Similarity score: -0.08190933614969254
Similarity score: -0.057533182203769684
Similarity score: -0.050888001918792725
Similarity score: -0.023818761110305786
Similarity score: -0.043379947543144226
Similarity score: -0.060681041330099106
Similarity score: -0.0278592798858881
Similarity score: -0.02566409483551979
Similarity score: 0.05532630532979965
Similarity score: 0.09655503928661346
Similarity score: 0.17081061005592346
Similarity score: 0.09689510613679886
Similarity score: -0.022674350067973137
Similarity score: 0.020018648356199265
Similarity score: -0.07616876810789108
Similarity score: -0.07143080979585648
Similarity score: 0.10311098396778107
Similarity score: 0.027786007151007652
Similarity score: 0.021053215488791466
Similarity score: 0.03909672424197197
Similarity score: 0.11884121596813202
Similarity score: 0.07102853059768677
Similarity score: 0.025014422833919525
Similarity score: -0.009094496257603168
Similarity score: -0.06334256380796432
Similarity score: -0.06562799215316772
Similarity score: 0.03923757001757622
Similarity score: -0.019943460822105408
Similarity score: -0.033838558942079544
Similarity score: -0.003272704314440489
Similarity score: 0.0064688571728765965
Similarity score: 0.014856875874102116
Similarity score: -0.060524556785821915
Similarity score: 0.08156011253595352
Similarity score: 0.07347297668457031

In [ ]:
1

In [ ]:
len(similarities)

In [ ]:
similarities#.sort(key=lambda x: x[1], reverse=True)

:

In [ ]:
# Step 3: Sort by similarity score (descending)
similarities.sort(key=lambda x: x[1], reverse=True)

# Step 4: Get top 3 matches
top_3 = similarities[:3]

# Step 5: Show results
print(f"\nQuery index: {query_idx} | Query name: {df.iloc[query_idx]['name']}")
print("\nTop 3 similar embeddings:")
for rank, (idx, score) in enumerate(top_3, 1):
    print(f"Rank {rank}: Index={idx}, Name={df.iloc[idx]['name']}, Similarity Score={score:.4f}")

# Optional: return values programmatically
top_3_indices = [idx for idx, _ in top_3]
top_3_scores = [score for _, score in top_3]

:

In [ ]:
1+1